### ISSUE TITLE
Finding attestation root keys by leveraging the "Web PKI"

### ISSUE THREAD

**Issue by cyberphone** [ietf-rats-wg/ietf-rats-usecases#3]
This is an extract of an earlier discussion on the RATS mailing list.

Attestations are great but suffer from the generic PKI problem: _Where are the trust anchors ?_
The Web PKI is nowadays carefully maintained by the platform vendors.  There is no counterpart for TEE attestation keys.

Some organizations are certainly prepared to go an extra mile to create their own repositories of trust anchors.

However, for those who lack incentives for maintaining trust anchor repositories an alternative approach seems feasible:
Add a URL like `https://huawei.com/tee-roots` to the attested data.  Consumers of such a scheme would then only have to configure a list of "trusted device vendors" expressed as Web domains like `huawei.com`, `google.com`, `apple.com` etc. in order to _securely retrieve trust anchors_ and verify attestations.  That is, the trust model for this concept is based on 1) device vendor selection 2) the ubiquity of the Web PKI.

**The text above is also supposed to qualify as a defensive publication.**

I would be interested in co-editing an I-D if there is a reasonable chance getting WG adoption for the work.

**Comment by mcr** [comment]
Hi, I am not really sure I understand what your solution entails.
In general, the webPKI CAs don't like additional claims being added to their system, and the browsers vendors are pretty powerful in keeping it that way.
I don't see how this proposal relates to the mostly defunct use case document: so please take this suggestion to the ML (where Note Well also applies).

**Comment by cyberphone** [comment]
Dear @mcr, this concept is already _firmly established_ for attestations of another kind:
https://developer.mozilla.org/en-US/docs/Web/Manifest

_"This information is necessary for the web app to be <br>downloaded and presented to the user similarly to a native app "_

That is, it is not about changing anything in the Web PKI it is about leveraging the trust in it. 

I'm personally using this for native payment apps:
https://webpki.github.io/w3cpay/payment-manifest.json
Google _mandates_ this arrangement.

Before taking this topic (again) to the mailing list (which one?) is it still unclear how it works?  What is RATS' method for locating attestation trust anchors?

BR AR

**Comment by cyberphone** [comment]
Attestation verifier algorithm:

**1.** Extract an "Authority URL" from the attested data
**2.** Verify that the "Authority URL" is based on the `https` scheme
**3.** Verify that the domain name (like `huawei.com`) of the "Authority URL" matches one in a list of _locally configured_ "Trusted Device Vendors"
**4.** If the "Authority URL" has not previously been accessed ("Authority URLs" **must** be versioned), retrieve and install the associated trust anchor
**5.** Validate the attestation signature key with the trust anchor associated with the "Authority URL".

If any of these steps fail the attestation is considered not trustworthy.

_Note that this scheme is independent of attestation key arrangements_.  The latter include hierarchical (like the PKI in Android) as well as one of the FIDO schemes (a single key vouching for hundreds of thousands of devices).

**Comment by mcr** [comment]
The IETF RATS WG can be found at https://datatracker.ietf.org/wg/rats, and the links to the mailing list are there.

**Comment by cyberphone** [comment]
@mcr I'm already on the mailing list and the topic has been raised as well:
https://mailarchive.ietf.org/arch/msg/rats/qth3-OexWYzA7mo4ZwMYYXPUuIg/
Based on the responses so far it is obvious that nobody understood this (IMO) pretty simple concept 😕
Would it be possible for you pointing out what the problem is with the 5-step algorithm above?  I would very much appreciate that!
@henkbirkholz

**Comment by henkbirkholz** [comment]
I have been summoned by utterance of my (github) username 😊

Hi Anders!

What if the Evidence does not include your proposed URL Claim (because I think we cannot mandate that)? I think you are describing a valid solution and are bringing this up in the context of use cases. Maybe the EAT I-D is the right place to talk about such a Claim?

**Comment by cyberphone** [comment]
Thanx Henk for taking a look on this!  That was the sole purpose of the issue; getting some kind of review before entertaining a WG or mailing list with an already dead horse 😁

EAT seems like a good choice for such a proposal.

Anders
